export { Header } from "./Header/index"
export { InfoBlock } from "./InformationBlock/index"
export { Advantages } from "./Advantages/index"
export { TextPromoPrizeBlock } from "./TextPromoPrizeBlock/index"
export { Quiz } from "./Quiz/index"
export { ImplantsList } from "./ImplantsList/index"
export { Answers } from "./Answers/index"