export { LINKS } from "./Links/links"
export { PHONE_NUMBERS } from "./PhoneNumbers/phoneNumbers"
export { HEADER_TEXT } from "./HeaderText/headerText"
export { INFO_BLOCK_TEXT } from "./InformationBlockText/informationBlockText"
export { ADVANTAGES_TEXT } from "./AdvantagesText/advantagesText"
export { QUESTIONS } from "./Questions/questions"
export { QUIZ_RESULT_TEXT } from "./QuizResultText/quizResultText"
export { IMPLANTS, IMPLANTS_TEXT } from "./ImplantsText/implantsText"
export { ANSWERS_TEXT } from "./AnswersText/answersText"
export { EXPERTS, EXPERTS_TEXT } from "./ExpertsText/expertsText"
export { INFO_CARD_TEXT } from "./InfoCardText/infoCardText"
export { CONSULTATION_TEXT, CONSULTATION_LIST } from "./ConsultationText/consulationText"
export { BEFORE_AFTER, BEFORE_AFTER_TEXT } from "./BeforeAfterText/beforeAfterText"
export { STAGES, STAGES_TEXT } from "./StagesText/stagesText"
export { REVIEWS_TEXT } from "./ReviewsText/reviewsText"