export { LINKS } from "./Links/links"
export { PHONE_NUMBERS } from "./PhoneNumbers/phoneNumbers"
export { HEADER_TEXT } from "./HeaderText/headerText"
export { INFO_BLOCK_TEXT } from "./InformationBlockText/informationBlockText"
export { ADVANTAGES_TEXT } from "./AdvantagesText/advantagesText"
export { QUESTIONS } from "./Questions/questions"
export { QUIZ_RESULT_TEXT } from "./QuizResultText/quizResultText"